import type { PageId } from '../types'

interface TutorialInternalProps {
  navigate: (id: PageId) => void
}

export default function TutorialInternal({ navigate }: TutorialInternalProps) {
  return (
    <>
      <div className="t-hero">
        <div className="t-hero-tag">Cursor · Boilerplate D</div>
        <h1>Design Team Hub</h1>
        <div className="t-hero-meta">Responsive web · 3 to 6 hours</div>
      </div>
      <div className="t-body">
        <button className="back-btn" onClick={() => { navigate('landing'); setTimeout(() => document.getElementById('surface-section')?.scrollIntoView({ behavior: 'smooth' }), 100) }}>← Choose a different surface</button>
        <div className="brief"><div className="brief-lbl">Brief</div><div className="brief-txt">The boilerplate for this tutorial is the page you are reading right now. coursera.design is the internal home for Design and Research — used by design managers, leadership, and the broader team to find resources, track initiatives, and understand what the org is working on. Your job today: take this structure and extend it. What would make this genuinely useful as a living team hub rather than a static intranet page?</div></div>
        <div className="t-img"><span style={{ fontSize: '24px' }}>🖼️</span><span className="lbl">Screenshot placeholder · Boilerplate D running in browser</span></div>

        <div className="phase-header"><div className="sec-label">Phase 0</div><div className="phase-title">Get set up before your first prompt</div><div className="phase-desc">These steps get Cursor open, your project running, and your brain oriented. Do them in order.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">A</div><div><div className="tstep-action">Duplicate the boilerplate and save your project</div><div className="tstep-body">Open the <strong>Google Drive app</strong> on your computer and find the shared <strong>AI Prototyping</strong> folder.<ul><li>Open <strong>Boilerplates</strong> and right-click <strong>boilerplate-d-internal</strong></li><li>Choose <strong>Make a copy</strong></li><li>Rename it to something like <strong>internal-yourname</strong></li><li>Move your copy into the <strong>Projects</strong> folder</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>📁</span><span className="tstep-img-lbl">Screenshot placeholder · Google Drive folder duplication</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">B</div><div><div className="tstep-action">Open the folder in Cursor</div><div className="tstep-body">Open Cursor. Go to <strong>File › Open Folder</strong> and navigate to your copy inside Google Drive. Select it and click Open.<ul><li>Wait for the spinner in the bottom-left to stop before moving on</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🖥️</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor with folder open</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">C</div><div><div className="tstep-action">Get your bearings in the Cursor interface</div><div className="tstep-body"><ul><li><strong>Left panel:</strong> file explorer — you will mostly work in <code>app</code> and <code>components</code></li><li><strong>Centre:</strong> the code editor — and where your Simple Browser lives. You'll rarely type here directly.</li><li><strong>Right panel / Cmd+L:</strong> the chat panel</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🗂️</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor interface annotated</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">D</div><div><div className="tstep-action">Set your model to Claude</div><div className="tstep-body"><ul><li>Click it and switch to one of the Claude models — Opus is a top performer right now if it's available</li><li>Auto rotates between models unpredictably — a fixed model gives you consistent results all day</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🤖</span><span className="tstep-img-lbl">Screenshot placeholder · Model selector</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">E</div><div><div className="tstep-action">Understand the four chat modes</div><div className="tstep-body"><ul><li><strong>Agent</strong> — reads files, writes code, makes changes. Use this for most prompts</li><li><strong>Ask</strong> — answers questions without changing anything</li><li><strong>Plan</strong> — previews what it will do before doing it</li><li><strong>Debug</strong> — tracks down errors</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>💬</span><span className="tstep-img-lbl">Screenshot placeholder · Chat mode selector</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">F</div><div><div className="tstep-action">Start the project and open it inside Cursor</div><div className="tstep-body">Make sure you are in <strong>Agent</strong> mode. Then send this prompt:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Open my simple browser and start my development server."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Cursor will install dependencies, start the server, and open your project in the Simple Browser — all in one go. If it asks you to confirm anything, click <strong>Accept</strong>.</div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🌐</span><span className="tstep-img-lbl">Screenshot placeholder · Simple Browser open inside Cursor</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">G</div><div><div className="tstep-action">Try your first prompt and see the loop in action</div><div className="tstep-body">In <strong>Agent</strong> mode, send this:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Add a new section below the hero called 'What's happening this week' with three placeholder items."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Watch the section appear in the browser. You just extended a real internal page — that's the whole loop.</div></div><div className="callout info"><div className="callout-icon">💡</div><div className="callout-text">If the browser does not refresh automatically, click the reload icon inside the Simple Browser panel.</div></div></div>

        <hr className="divider" />
        <div className="phase-header"><div className="sec-label">Phase 1</div><div className="phase-title">Understand what you are working with</div><div className="phase-desc">The boilerplate is a real internal page — not a hypothetical. Before extending it, understand what it already does and who it is for.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">1</div><div><div className="tstep-action">Ask Cursor to explain the project</div><div className="tstep-body">Switch to <strong>Ask</strong> mode and send this prompt.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Explain this project to me like I am a designer who does not write code. What does each file and folder do? What would I see in the browser if I changed something in each one?"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">2</div><div><div className="tstep-action">Inspect the nav and page structure</div><div className="tstep-body">Open <code>components/Nav.tsx</code> in the file explorer. Stay in <strong>Ask</strong> mode and send this:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"What controls the navigation and the overall page sections? If I wanted to add a new top-level section to the site — like a team directory or a projects page — what would I need to add or change?"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">3</div><div><div className="tstep-action">Look at the boilerplate as a design manager would</div><div className="tstep-body">Spend two minutes in the Simple Browser as someone who would actually use this page.<ul><li>What can you find quickly? What takes too long?</li><li>What is missing that would make this genuinely useful?</li><li>Who is this page talking to — everyone, or a specific person?</li></ul></div></div></div><div className="callout info"><div className="callout-icon">💡</div><div className="callout-text"><strong>Debugging tip:</strong> If something looks broken, take a screenshot and drag it into the Cursor chat. Ask: <em>"This is what I'm seeing. What went wrong and how do I fix it?"</em></div></div></div>

        <hr className="divider" />
        <div className="phase-header"><div className="sec-label">Phase 2</div><div className="phase-title">Connect Figma, then build toward your spec</div><div className="phase-desc">Frame 1 in your companion Figma file is the current page — the boilerplate you just set up. Frame 2 is a redesigned version with a team directory section and a project status board. You will build toward it.</div></div>
        <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '12px', overflow: 'hidden', marginBottom: '20px' }}>
          <div style={{ background: '#1E1E1E', padding: '16px 20px', display: 'flex', alignItems: 'center', gap: '10px' }}><span style={{ fontSize: '16px' }}>🎨</span><div><div style={{ fontSize: '12px', fontWeight: 600, color: '#fff', marginBottom: '2px' }}>Your companion Figma file</div><div style={{ fontSize: '11px', color: '#888' }}>Open this before starting Phase 2 · Link TBD</div></div></div>
          <div style={{ padding: '16px 20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '80px', background: 'linear-gradient(135deg, #2a1a00, #B45309)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><span style={{ fontSize: '11px', fontWeight: 600, color: 'rgba(255,255,255,0.6)', letterSpacing: '0.06em', textTransform: 'uppercase' as const }}>Already rendered</span></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 1 · Current hub</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>This is your starting point.</div></div></div>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '80px', background: 'linear-gradient(135deg, #F5F7FA, #E8ECF0)', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' as const }}><span style={{ fontSize: '11px', fontWeight: 600, color: '#9AA0AA', letterSpacing: '0.06em', textTransform: 'uppercase' as const }}>Build toward this</span><div style={{ position: 'absolute' as const, top: '8px', right: '8px', background: '#FFF3CD', color: '#92600A', fontSize: '9px', fontWeight: 600, padding: '2px 6px', borderRadius: '3px', letterSpacing: '0.04em' }}>IN FIGMA</div></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 2 · Extended hub</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>Team directory + project status board added. Your build target.</div></div></div>
          </div>
          <div style={{ padding: '12px 20px', borderTop: '0.5px solid #E8E8E8', background: '#FAFAFA' }}><div style={{ fontSize: '11px', color: '#5F6B7A', lineHeight: 1.55 }}>The file uses the <strong>CDS design system library</strong>, already connected.</div></div>
        </div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">4</div><div><div className="tstep-action">Connect the Figma MCP to Cursor</div><div className="tstep-body"><ul><li>Open Cursor Settings with <strong>Cmd+,</strong> and go to the <strong>MCP</strong> tab</li><li>Click <strong>Add MCP Server</strong> and select <strong>Figma</strong></li><li>Follow the authentication steps and return to the chat panel</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🔗</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor MCP settings with Figma connected</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">5</div><div><div className="tstep-action">Point Cursor at Frame 2 and build it</div><div className="tstep-body">In Figma, switch to <strong>Dev mode</strong>, select <strong>Frame 2 · Extended hub</strong>, copy the frame link, and send this in <strong>Agent</strong> mode.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Using the Figma MCP, read Frame 2 from this link: [link to frame]. Add the two new sections from this design to the existing page — a team directory and a project status board — matching the layout, spacing, and components. Keep everything that already exists. Tell me what you built and flag anything you could not replicate."</div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🎨</span><span className="tstep-img-lbl">Screenshot placeholder · Frame 2 alongside extended hub in Simple Browser</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">6</div><div><div className="tstep-action">Test the new sections</div><div className="tstep-body">Scroll through the page and confirm both new sections appear, the layout matches Frame 2, and the existing content is intact. Drag a screenshot into Cursor chat to fix any gaps.</div></div></div></div>

        <hr className="divider" />
        <div className="phase-header"><div className="sec-label">Phase 3</div><div className="phase-title">Go wide — build something new without a spec</div><div className="phase-desc">The spec extended the page with two new sections. Now think about what would make coursera.design genuinely useful to the people who would actually use it — and build one of those things.</div></div>
        <div className="dir-grid">
          <div className="dir-card"><div className="dir-label">Direction 1</div><div className="dir-title">Design principles</div><div className="dir-prompt">"Add a section that surfaces Coursera's design principles — five of them, each with a one-line description. They should feel like something the team actually believes, not a compliance poster."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 2</div><div className="dir-title">Recent work</div><div className="dir-prompt">"Add a 'Recently shipped' section with three items — a project name, a one-sentence description, and a 'View →' link. It should feel like a living record of what the team has done, not a portfolio."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 3</div><div className="dir-title">New joiner path</div><div className="dir-prompt">"Add a section specifically for new joiners — three or four links to the most important things they would need in their first two weeks. Label it clearly as being for new team members."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 4</div><div className="dir-title">Search</div><div className="dir-prompt">"Add a simple search bar to the top of the page. When the learner types, it should filter the visible sections and cards by matching text. It doesn't need to be perfect — it just needs to feel fast."</div></div>
        </div>

        <div className="optional-block">
          <div className="optional-block-head">
            <div style={{ fontSize: '13px', fontWeight: 500 }}>Optional · Send your concepts back to Figma</div>
            <div style={{ fontSize: '10px', fontWeight: 500, letterSpacing: '0.06em', textTransform: 'uppercase' as const, color: '#9AA0AA' }}>Experimental</div>
          </div>
          <div className="optional-block-body">
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>You can send your concepts from your Cursor prototype directly to Figma as editable layers — not a screenshot. The result may not be pixel-perfect, but it gives you real frames you can annotate, duplicate, and design on top of. For best results, switch your model to <strong>claude-opus-4-6</strong> before running this step.</div>
            <div className="optional-inner-prompt tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Capture the UI in a new frame in Figma here: [link to page in Figma]."</div></div>
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>Cursor may ask you to approve or run something — click through whatever it needs. A small Figma capture toolbar will appear at the top of your browser. Navigate to the state you want to capture, then click <strong>Entire screen</strong> to send it to Figma.</div>
            <div style={{ background: '#FFFBF0', borderRadius: '6px', padding: '10px 14px', fontSize: '12px', color: '#92600A', lineHeight: 1.55 }}>The layers in Figma will be editable but may not match your design system exactly. Treat this as a starting point for refinement, not a finished handoff.</div>
          </div>
        </div>

        <hr className="divider" />
        <div className="tips-box">
          <div className="sec-label" style={{ marginBottom: '12px' }}>Prompting tips</div>
          <div className="ri">Describe what you <em>see</em>, not what you think the code should do. "The team directory cards feel too dense" beats "reduce padding to 12px".</div>
          <div className="ri">One change at a time. Multi-part prompts produce messy results.</div>
          <div className="ri">If something breaks: "That broke the layout. Undo that change and let's try a different approach."</div>
          <div className="ri">If the output is close: "That's close. The section header should match the style of the others above it." Iterate from what it gave you.</div>
          <div className="ri">Cmd+Z undoes Cursor's changes like any other edit.</div>
        </div>
        <div className="reflect">
          <div className="reflect-lbl">Reflect</div>
          <div className="ri">What did Cursor build correctly without you asking? What did it get wrong or miss?</div>
          <div className="ri">When Cursor pulled from Figma — what translated well? What did it struggle to replicate?</div>
          <div className="ri">Show what you built to someone on the team who would actually use coursera.design. What did they say?</div>
          <div className="ri">What is the difference between a useful internal tool and one that just looks good? Did you build the right one?</div>
          <div className="ri">What would you explore next if you had another hour?</div>
        </div>
        <div style={{ borderTop: '0.5px solid #E8E8E8', paddingTop: '32px', marginTop: '32px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap' as const, gap: '12px' }}>
          <div><div style={{ fontSize: '14px', fontWeight: 500, marginBottom: '4px' }}>You're done. Share what you made.</div><div style={{ fontSize: '13px', color: '#9AA0AA' }}>Your submission appears in the team gallery — others can see your work and reach out.</div></div>
          <button onClick={() => { navigate('landing'); setTimeout(() => document.getElementById('gallery-section')?.scrollIntoView({ behavior: 'smooth' }), 100) }} style={{ background: '#0056D2', color: '#fff', border: 'none', borderRadius: '8px', padding: '12px 20px', fontSize: '13px', fontWeight: 500, cursor: 'pointer', fontFamily: 'inherit', flexShrink: 0 }}>Submit your project →</button>
        </div>
      </div>
    </>
  )
}
