import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import SubmitDialog from '../components/SubmitDialog'
import PhaseNav from '../components/PhaseNav'
import TutorialEnd from '../components/TutorialEnd'
import { useSubmissions } from '../lib/submissions'

export default function TutorialDiscovery() {
  const navigate = useNavigate()
  const { submitProject } = useSubmissions()
  const [dialogOpen, setDialogOpen] = useState(false)
  return (
    <>
      <div className="t-hero">
        <div className="t-hero-tag">Cursor · Boilerplate A</div>
        <h1>Course Discovery</h1>
        <div className="t-hero-meta">Responsive web · 3 to 6 hours</div>
      </div>
      <PhaseNav />
      <div className="t-body">
        <div className="brief"><div className="brief-lbl">Brief</div><div className="brief-txt">Coursera's homepage has a search bar. But search assumes the learner already knows what they want — and most don't. Your job today: build a discovery experience that starts with a conversation. The boilerplate gives you a working landing page with a conversational input. Phase 2 asks you to bring the response to life — a loading state, then a two-panel view where an AI overview and a course grid appear together. Make it feel like the platform is thinking with the learner, not just matching keywords.</div></div>
        <div className="t-img"><span style={{ fontSize: '24px' }}>🖼️</span><span className="lbl">Screenshot placeholder · Boilerplate A running in browser</span></div>

        <div id="phase-0" className="phase-header"><div className="sec-label">Phase 0</div><div className="phase-title">Get set up before your first prompt</div><div className="phase-desc">These steps get Cursor open, your project running, and your brain oriented. Do them in order.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">A</div><div><div className="tstep-action">Download the boilerplate and save your project</div><div className="tstep-body">Download the starter file for this tutorial and unzip it on your machine. You will be working locally for the whole day — no cloud setup needed right now.<ul><li>Download the zip file from <a href="https://drive.google.com/file/d/1j0EWVNb1BrOhRI-uN54eMEUBETBf7Lkm/view?usp=drive_link" target="_blank" rel="noreferrer"><strong>Boilerplate-Discovery-Start.zip</strong></a></li><li>Unzip it — you should see a folder called <strong>boilerplate-a-discovery</strong></li><li>Rename it to something like <strong>discovery-yourname</strong></li><li>Move it somewhere easy to find, like your <strong>Desktop</strong> or <strong>Documents</strong> folder</li></ul>At the end of the day, you can upload your project folder to your personal Google Drive as a backup, or follow the advanced Phase 4 steps to push it to GitHub. Don't worry about that now.</div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">B</div><div><div className="tstep-action">Open the folder in Cursor</div><div className="tstep-body">Open Cursor. Go to <strong>File › Open Folder</strong> and navigate to your renamed project folder. Select it and click Open.<ul><li>Cursor will read through the files — you will see a spinner in the bottom-left corner</li><li>Wait for it to stop before moving on</li></ul></div></div></div><div className="tstep-img"><img src="/open-project.png" alt="Cursor start screen showing Open project, Clone repo, and Connect via SSH options" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">C</div><div><div className="tstep-action">Get your bearings in the Cursor interface</div><div className="tstep-body">Take a minute to look around before touching anything.<ul><li><strong>Left panel:</strong> the file explorer — every file in your project. You will mostly work inside <code>app</code> and <code>components</code></li><li><strong>Centre:</strong> the code editor — and where your Simple Browser lives. You'll rarely type here directly.</li><li><strong>Right panel / Cmd+L:</strong> the chat panel — this is where you direct Cursor in plain English</li></ul></div></div></div><div className="tstep-img"><img src="/cursor-interface.png" alt="Cursor interface with file explorer on the left, editor in the centre, and chat panel on the right" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">D</div><div><div className="tstep-action">Set your model to Claude</div><div className="tstep-body">In the chat panel, find the model selector near the top. It may say <strong>Auto</strong> by default.<ul><li>Click it and switch to <strong>claude-opus-4-6-high</strong> (sometimes listed as Opus High) — it is the most capable model and a great default for complex prompts</li><li>For quicker, lower-effort tasks — simple text changes, small CSS tweaks, renaming things — switch to <strong>Opus Medium</strong>. It is faster and uses fewer credits. You can switch between them anytime</li><li>Avoid leaving it on <strong>Auto</strong>, which rotates between models unpredictably — picking a model yourself gives you more consistent results all day</li></ul></div></div></div><div className="tstep-img"><img src="/change-model.png" alt="Cursor model selector showing where to change from Auto to a specific model" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">E</div><div><div className="tstep-action">Understand the four chat modes</div><div className="tstep-body">At the top of the chat panel you will see four modes.<ul><li><strong>Agent</strong> — reads your files, writes code, makes changes. Use this for most prompts</li><li><strong>Ask</strong> — answers questions without changing anything. Use it when you want to understand before acting</li><li><strong>Plan</strong> — shows you what it intends to do before doing it. Useful for bigger changes</li><li><strong>Debug</strong> — helps track down errors. You can ignore it for now</li></ul></div></div></div><div className="tstep-img"><img src="/chat-modes.png" alt="Cursor chat mode selector showing Agent, Plan, Debug, and Ask options" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">F</div><div><div className="tstep-action">Start the project and open it inside Cursor</div><div className="tstep-body">Make sure you are in <strong>Agent</strong> mode. Then send this prompt:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Open my simple browser and start my development server."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Cursor will install dependencies, start the server, and open your project in the Simple Browser — all in one go. If it asks you to confirm anything, click <strong>Run</strong>.</div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text">You may see a warning about a Node file that cannot be opened — this is harmless. Dismiss it or move it to Trash and carry on.</div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>You can also use Chrome or any external browser.</strong> The dev server runs on a local address like <code>http://localhost:5173</code> — copy that URL from the Simple Browser's address bar and open it in Chrome. This gives you access to Chrome DevTools for inspecting elements, checking layout, and debugging alongside Cursor.</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">G</div><div><div className="tstep-action">Try your first prompt and see the loop in action</div><div className="tstep-body">Stay in <strong>Agent</strong> mode and send this:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Change the placeholder text in the input to 'What do you want to be able to do?' and make the suggestion chips below it more specific — career goals rather than topics."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Watch the file on the left update, then look at the Simple Browser — it should refresh automatically. That loop is the entire workflow for the day: write a prompt, see the update, react to what you got.</div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text">If the browser does not refresh automatically, click the reload icon inside the Simple Browser panel.</div></div></div>

        <hr className="divider" />
        <div id="phase-1" className="phase-header"><div className="sec-label">Phase 1</div><div className="phase-title">Understand what you are working with</div><div className="phase-desc">Before changing anything significant, get a clear picture of what the boilerplate contains.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">1</div><div><div className="tstep-action">Ask Cursor to explain the project</div><div className="tstep-body">Switch to <strong>Ask</strong> mode and send this prompt. Read the full response before moving on. This is a good moment to switch your model to <strong>Opus Medium</strong> — Ask mode questions don't need the full power of Opus High, and it's faster.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Explain this project to me like I am a designer who does not write code. What does each file and folder do? What would I see in the browser if I changed something in each one?"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">2</div><div><div className="tstep-action">Click on elements and tweak the CSS</div><div className="tstep-body">The browser inspector lets you edit CSS values directly on the page in real time — try changing a border radius, a colour, or a font size. The changes appear instantly. This is useful for quick visual experiments where you want to see something before committing to it.<br /><br />Click the <strong>inspector icon</strong> in the top-right corner of the Simple Browser to activate it — it looks like this: <img src="/inspector-icon.png" alt="Inspector icon" style={{ height: '40px', verticalAlign: 'middle', borderRadius: '4px', margin: '0 2px' }} /> — then click any element on the page. A panel opens showing its CSS: colours, padding, font size, border radius, spacing.<br /><br />When you find something you like, you have two options:<ul><li><strong>Click Apply</strong> — the inspector writes the change directly into the file. Fast, no prompting required. The risk: it can be imprecise — inspectors sometimes apply changes to the wrong selector or create inline styles that conflict with your stylesheet later. Good for small, confident tweaks.</li><li><strong>Describe it to Cursor</strong> — tell Cursor what you want in plain language: <em>"Make the cards rounder"</em> or <em>"Increase the heading font size to match the hierarchy in the rest of the page."</em> Cursor finds the right place in the code and makes a clean, permanent change. Slower, but more reliable — especially for anything structural or anything you might want to revisit later.</li></ul>A good rule of thumb: use the inspector to explore, use Cursor to commit.</div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">3</div><div><div className="tstep-action">Know which mode to use and when</div><div className="tstep-body">You learned about the four modes in Phase 0. Here is how to think about them for the rest of the day:<ul><li><strong>Ask</strong> — when you want to understand a file or component before touching it. "What does this component do? What data does it use?"</li><li><strong>Plan</strong> — when you have an idea and want to iterate on the approach before committing. "I want to redesign this layout — what are my options?" Plan shows you what it would do and lets you refine before it executes</li><li><strong>Agent</strong> — when you are ready to implement. "Change the layout and add a loading state." Agent reads your files, writes code, and makes the change</li></ul>A good rhythm: <strong>Ask</strong> to understand, <strong>Plan</strong> to iterate, <strong>Agent</strong> to build.<br /><br />Spend a minute clicking around the boilerplate in the Simple Browser. What is the most important thing on the page? What feels unfinished? Keep that in mind as you move into Phase 2.</div></div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>Debugging tip:</strong> If something looks broken at any point, take a screenshot and drag it into the Cursor chat. Ask: <em>"This is what I'm seeing. What went wrong and how do I fix it?"</em> Cursor can read the screenshot and diagnose the issue directly.</div></div></div>

        <hr className="divider" />
        <div id="phase-2" className="phase-header"><div className="sec-label">Phase 2</div><div className="phase-title">Connect Figma, then build toward your spec</div><div className="phase-desc">Frame 1 in your companion Figma file is the landing page with the conversational input — already running as your boilerplate. Frame 2 is the response experience: a loading state that transitions into a two-panel view with an AI overview on the left and a course grid on the right. You will build toward it.</div></div>
        <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '12px', overflow: 'hidden', marginBottom: '20px' }}>
          <div style={{ background: '#1E1E1E', padding: '16px 20px', display: 'flex', alignItems: 'center', gap: '10px' }}><span style={{ fontSize: '16px' }}>🎨</span><div><div style={{ fontSize: '12px', fontWeight: 600, color: '#fff', marginBottom: '2px' }}>Your companion Figma file</div><div style={{ fontSize: '11px', color: '#888' }}>Open this before starting Phase 2 · <a href="https://www.figma.com/design/WCWh3OsRn1bvFxG4XGOQGv/AI-Learning-Day---Figma-companion-file--Discovery--Make-a-copy-?node-id=0-1&t=0urh2hbxGwIaxJKu-1" target="_blank" rel="noreferrer" style={{ color: '#6B9FFF', textDecoration: 'underline' }}>Open in Figma</a></div></div></div>
          <div style={{ padding: '16px 20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '140px', overflow: 'hidden', position: 'relative' as const }}><img src="/discovery-frame1.png" alt="Coursera discovery landing page with conversational input" style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top', display: 'block' }} /><div style={{ position: 'absolute' as const, bottom: '8px', left: '8px', background: '#0056D2', color: '#fff', fontSize: '9px', fontWeight: 600, padding: '2px 7px', borderRadius: '3px', letterSpacing: '0.04em' }}>BUILT IN CURSOR</div></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 1 · Conversational landing</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>Input, headline, suggestion chips.</div></div></div>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '140px', overflow: 'hidden', position: 'relative' as const }}><img src="/discovery-frame2.png" alt="Coursera discovery results view with AI overview and course grid" style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top', display: 'block' }} /><div style={{ position: 'absolute' as const, bottom: '8px', left: '8px', background: '#FFF3CD', color: '#92600A', fontSize: '9px', fontWeight: 600, padding: '2px 7px', borderRadius: '3px', letterSpacing: '0.04em' }}>READY IN FIGMA</div></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 2 · Discovery results</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>Loading state → AI overview + course grid. Your build target.</div></div></div>
          </div>
          <div style={{ padding: '12px 20px', borderTop: '0.5px solid #E8E8E8', background: '#FAFAFA' }}><div style={{ fontSize: '11px', color: '#5F6B7A', lineHeight: 1.55 }}>The boilerplate includes a <strong>Tailwind config</strong> with CDS colours, typography, and spacing tokens. Cursor will build custom components to match your Figma spec using these tokens — so the output should feel very close to the design. It won't use the coded CDS component library, which requires a more complex front-end setup that's out of scope for today. More on this soon as we develop design-engineering workflows.</div></div>
        </div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">4</div><div><div className="tstep-action">Connect the Figma MCP to Cursor</div><div className="tstep-body">Once connected, Cursor can read any frame in your Figma file directly — layout, styles, content — without you having to describe any of it.<ul><li>Open Cursor Settings with <strong>Cmd+,</strong> and go to the <strong>MCP</strong> tab</li><li>Click <strong>Add MCP Server</strong> and select <strong>Figma</strong></li><li>Follow the authentication steps</li><li>Once Figma shows as connected, come back to the chat panel</li></ul></div></div></div><div className="tstep-img"><img src="/cursor-mcp-settings.png" alt="Cursor Tools & MCP settings showing Figma connected with 13 tools enabled" /></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>Where to find the Figma link for your prompts:</strong> In Figma, switch to <strong>Dev mode</strong> using the toggle in the bottom toolbar (while in Edit mode). You have two options: right-click a frame and choose <strong>Copy link</strong>, or select the frame and click <strong>Copy example prompt</strong> in the right panel — either gives you the link to paste into Cursor.</div></div><div className="tstep-img"><img src="/figma-dev-mode.png" alt="Figma toolbar showing the Dev Mode toggle in the top-right corner" /><img src="/figma-mcp-panel.png" alt="Figma MCP panel showing the Copy example prompt with a Figma file link" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">5</div><div><div className="tstep-action">Wire up the loading state</div><div className="tstep-body">Send this prompt in <strong>Agent</strong> mode. It connects the search bar submission to the loading state layout in Figma.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Wire up the search bar submission to transition to the loading state. Use this Figma file for the layout: [link to frame]"</div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text">If errors appear in the browser or terminal, take a screenshot, drag it into the Cursor chat, and ask it to fix what went wrong.</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">6</div><div><div className="tstep-action">Implement the responsive views</div><div className="tstep-body">Send this prompt to implement the responsive layout from Figma.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Implement the responsive view according to this design from Figma: [link to frame]"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">7</div><div><div className="tstep-action">Render the two-panel results view</div><div className="tstep-body">Send this prompt to transition out of the loading state into the full results layout with mocked content.<br /><br />Like the loading state, the Figma frame only shows you a single frozen moment — two panels, some cards, some text. It cannot tell Cursor how the panels should scroll relative to each other, what the mocked content should actually say, or which panel should stay fixed while the other scrolls. The extra detail in this prompt fills in those decisions, so Cursor builds something that behaves correctly rather than just looking roughly right.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Transition out of the loading state into the two-panel layout with mocked data. Use this Figma frame for the layout: [link to frame]{'\n\n'}Left panel: static AI overview text and a follow-up question.{'\n'}Right panel: 3-column grid of hardcoded course cards with a title, partner name, rating, and badge."</div></div>
        <div className="callout warn"><div className="callout-header"><span className="callout-icon">⚠️</span><span className="callout-label">Heads up</span></div><div className="callout-text"><strong>Check these two things before moving on.</strong> They are the layout details most likely to drift from the Figma:<ul style={{ marginTop: '6px', paddingLeft: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '4px' }}><li style={{ paddingLeft: '14px', position: 'relative' }}><span style={{ position: 'absolute', left: 0 }}>·</span> The card grid scrolls independently of the left panel</li><li style={{ paddingLeft: '14px', position: 'relative' }}><span style={{ position: 'absolute', left: 0 }}>·</span> The left panel input bar sits fixed at the bottom</li></ul>If either looks wrong, try selecting the element in the browser, copying its class name, and telling Cursor to correct it directly. For example:<br /><br /><code style={{ fontSize: '11px', background: '#F0F4FF', padding: '2px 6px', borderRadius: '4px' }}>{"<div> .px-16 the input should be sticky to the bottom of the viewport"}</code><br /><code style={{ fontSize: '11px', background: '#F0F4FF', padding: '2px 6px', borderRadius: '4px', marginTop: '4px', display: 'inline-block' }}>{"<header> .flex the header is sticky to the top"}</code></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">8</div><div><div className="tstep-action">Fix broken or missing assets</div><div className="tstep-body">When building from a Figma file, some assets may not transfer cleanly — images might be missing, icons could render as blank boxes, or fonts may fall back to system defaults. This is normal and easy to fix.<ul><li>If an <strong>image is missing</strong>, find the original in Figma, export it as PNG or SVG, and drag it into your project's <code>public</code> folder. Then tell Cursor: <em>"Use the image I just added in public/[filename] for the hero banner"</em></li><li>If an <strong>icon is missing</strong> or looks wrong, tell Cursor what you need: <em>"The search icon is missing. Add a search icon there using Material Symbols"</em></li><li>If <strong>fonts look wrong</strong>, take a screenshot and ask Cursor to fix the mismatch</li><li>If <strong>colours are off</strong>, use the inspector from Step 2 to compare what you see against the Figma file, then ask Cursor to correct specific values</li></ul></div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">9</div><div><div className="tstep-action">Test the full flow</div><div className="tstep-body">Type a query into the input and submit it. Walk through the full sequence: input → loading state → two-panel results. Check the layout against the Figma frames at each step. If something looks off, drag a screenshot into the Cursor chat and ask it to fix the gap.</div></div></div></div>

        <hr className="divider" />
        <div id="phase-3" className="phase-header"><div className="sec-label">Phase 3</div><div className="phase-title">Go wide — build something new without a spec</div><div className="phase-desc">Phase 2 was about accuracy: reading a design and building it faithfully. Phase 3 is the opposite. Put the Figma file away, pick a direction, and push the experience further than the spec describes.</div></div>
        <div className="callout info standalone"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>Plan mode shines here.</strong> Phase 3 is open-ended — there is no spec to follow. Before jumping into Agent mode, try sending your direction prompt in <strong>Plan</strong> mode first. It will lay out what it intends to change and you can refine the approach before it writes any code. This is especially useful when you are exploring ideas and want to steer before committing.</div></div>
        <div className="dir-grid">
          <div className="dir-card"><div className="dir-label">Direction 1</div><div className="dir-title">Query awareness</div><div className="dir-prompt">"The AI overview currently shows placeholder text. Make it respond to what the learner actually typed — if they said 'I want to work in data', the overview should reflect that. The response should feel like it was written for them."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 2</div><div className="dir-title">Refine and follow-up</div><div className="dir-prompt">"After the results appear, add a way for the learner to refine their query without going back to the start — a small input or a set of follow-up chips like 'More beginner-friendly' or 'Shorter courses'. The page should update in place."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 3</div><div className="dir-title">Loading as communication</div><div className="dir-prompt">"The loading state currently feels like a spinner. Make it communicate what is happening — 'Finding courses for your goal', 'Reviewing 3,000+ options' — so the wait feels purposeful rather than blank."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 4</div><div className="dir-title">Confidence signals</div><div className="dir-prompt">"Add a subtle indicator to each course card that explains why it was recommended — 'Matches your goal', 'Most popular for career changers', 'Short enough to finish this month'. Keep it minimal — one line per card at most."</div></div>
        </div>

        <div className="optional-block">
          <div className="optional-block-head">
            <div style={{ fontSize: '13px', fontWeight: 500 }}>Optional · Send your concepts back to Figma</div>
            <div style={{ fontSize: '10px', fontWeight: 500, letterSpacing: '0.06em', textTransform: 'uppercase' as const, color: '#9AA0AA' }}>Experimental</div>
          </div>
          <div className="optional-block-body">
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>You can send your concepts from your Cursor prototype directly to Figma as editable layers — not a screenshot. The result may not be pixel-perfect, but it gives you real frames you can annotate, duplicate, and design on top of. For best results, switch your model to <strong>claude-opus-4-6</strong> before running this step.</div>
            <div className="optional-inner-prompt tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Capture the UI in a new frame in Figma here: [link to page in Figma]."</div></div>
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>Cursor may ask you to approve or run something — click through whatever it needs. A small Figma capture toolbar will appear at the top of your browser. Navigate to the state you want to capture, then click <strong>Entire screen</strong> to send it to Figma.</div>
            <div style={{ background: '#FFFBF0', borderRadius: '6px', padding: '10px 14px', fontSize: '12px', color: '#92600A', lineHeight: 1.55 }}>The layers in Figma will be editable but may not match your design system exactly. Treat this as a starting point for refinement, not a finished handoff.</div>
          </div>
        </div>

        <hr className="divider" />
        <div className="tips-box">
          <div className="sec-label" style={{ marginBottom: '12px' }}>Prompting tips</div>
          <div className="ri">Describe what you <em>see</em>, not what you think the code should do. "The loading state feels too abrupt" beats "add a 300ms delay".</div>
          <div className="ri">One change at a time. Multi-part prompts produce messy results.</div>
          <div className="ri">If something breaks: "That broke the layout. Undo that change and let's try a different approach."</div>
          <div className="ri">If the output is close: "That's close. The AI overview should feel more like a response and less like a label." Iterate from what it gave you.</div>
          <div className="ri">Cmd+Z undoes Cursor's changes like any other edit.</div>
        </div>
        <div className="reflect">
          <div className="reflect-lbl">Reflect</div>
          <div className="ri">What did Cursor build correctly without you asking? What did it get wrong or miss?</div>
          <div className="ri">When Cursor pulled from Figma — what translated well? What did it struggle to replicate?</div>
          <div className="ri">Go to coursera.org and try the real search. What does your version do that the real one does not? What did you lose?</div>
          <div className="ri">If a learner typed "I don't know where to start" into your input, what would they see? Is that the right response?</div>
          <div className="ri">What would you explore next if you had another hour?</div>
        </div>
        <TutorialEnd onSubmit={() => setDialogOpen(true)} />
      </div>
      <SubmitDialog open={dialogOpen} onClose={() => setDialogOpen(false)} onSubmit={(data) => { submitProject(data); navigate('/', { state: { scrollTo: 'gallery-section' } }) }} />
    </>
  )
}
