import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import SubmitDialog from '../components/SubmitDialog'
import PhaseNav from '../components/PhaseNav'
import TutorialEnd from '../components/TutorialEnd'
import { useSubmissions } from '../lib/submissions'

export default function TutorialCourseFrame() {
  const navigate = useNavigate()
  const { submitProject } = useSubmissions()
  const [dialogOpen, setDialogOpen] = useState(false)
  return (
    <>
      <div className="t-hero">
        <div className="t-hero-tag">Cursor · Boilerplate C</div>
        <h1>Learning Environment</h1>
        <div className="t-hero-meta">Responsive web · 3 to 6 hours</div>
      </div>
      <PhaseNav />
      <div className="t-body">
        <div className="brief"><div className="brief-lbl">Brief</div><div className="brief-txt">The course frame is where learners spend most of their time on Coursera — and it has barely changed in years. The boilerplate gives you a three-panel shell: a reading pane, a video pane, and a working AI chatbot. Your job today: challenge the hierarchy. Who is in charge — the content, the learner, or the AI? What happens when you rethink which panel gets the most space, or when the AI speaks first?</div></div>
        <div className="t-img"><span style={{ fontSize: '24px' }}>🖼️</span><span className="lbl">Screenshot placeholder · Boilerplate C running in browser</span></div>

        <div id="phase-0" className="phase-header"><div className="sec-label">Phase 0</div><div className="phase-title">Get set up before your first prompt</div><div className="phase-desc">These steps get Cursor open, your project running, and your brain oriented. Do them in order.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">A</div><div><div className="tstep-action">Download the boilerplate and save your project</div><div className="tstep-body">Download the starter file for this tutorial and unzip it on your machine. You will be working locally for the whole day — no cloud setup needed right now.<ul><li>Download the zip file from <strong>[link TBD]</strong></li><li>Unzip it — you should see a folder called <strong>boilerplate-c-courseframe</strong></li><li>Rename it to something like <strong>courseframe-yourname</strong></li><li>Move it somewhere easy to find, like your <strong>Desktop</strong> or <strong>Documents</strong> folder</li></ul>At the end of the day, you can upload your project folder to your personal Google Drive as a backup, or follow the advanced Phase 4 steps to push it to GitHub. Don't worry about that now.</div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">B</div><div><div className="tstep-action">Open the folder in Cursor</div><div className="tstep-body">Open Cursor. Go to <strong>File › Open Folder</strong> and navigate to your renamed project folder. Select it and click Open.<ul><li>Wait for the spinner in the bottom-left to stop before moving on</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🖥️</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor with folder open</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">C</div><div><div className="tstep-action">Get your bearings in the Cursor interface</div><div className="tstep-body"><ul><li><strong>Left panel:</strong> file explorer — you will mostly work in <code>app</code> and <code>components</code></li><li><strong>Centre:</strong> the code editor — and where your Simple Browser lives. You'll rarely type here directly.</li><li><strong>Right panel / Cmd+L:</strong> the chat panel</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🗂️</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor interface annotated</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">D</div><div><div className="tstep-action">Set your model to Claude</div><div className="tstep-body">In the chat panel, find the model selector near the top. It may say <strong>Auto</strong> by default.<ul><li>Click it and switch to <strong>claude-opus-4-6-high</strong> (sometimes listed as Opus High) — it is the most capable model and a great default for complex prompts</li><li>For quicker, lower-effort tasks — simple text changes, small CSS tweaks, renaming things — switch to <strong>Opus Medium</strong>. It is faster and uses fewer credits. You can switch between them anytime</li><li>Avoid leaving it on <strong>Auto</strong>, which rotates between models unpredictably — picking a model yourself gives you more consistent results all day</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🤖</span><span className="tstep-img-lbl">Screenshot placeholder · Model selector</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">E</div><div><div className="tstep-action">Understand the four chat modes</div><div className="tstep-body"><ul><li><strong>Agent</strong> — reads files, writes code, makes changes. Use this for most prompts</li><li><strong>Ask</strong> — answers questions without changing anything</li><li><strong>Plan</strong> — previews what it will do before doing it</li><li><strong>Debug</strong> — tracks down errors</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>💬</span><span className="tstep-img-lbl">Screenshot placeholder · Chat mode selector</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">F</div><div><div className="tstep-action">Add your Anthropic API key</div><div className="tstep-body">The boilerplate ships with a working AI chatbot. It needs one thing to activate: your Anthropic API key.<ul><li>In the file explorer, open <strong>.env.local</strong> at the root of the project</li><li>You will see a line that reads <code>NEXT_PUBLIC_ANTHROPIC_API_KEY=</code></li><li>Paste your API key after the equals sign — no spaces, no quotes</li><li>Save the file</li></ul>Your key stays on your machine and is never committed to the shared folder.</div></div></div><div className="callout warn"><div className="callout-icon">⚠️</div><div className="callout-text">Don't have an API key yet? Get one at <strong>console.anthropic.com</strong>. Free-tier access is enough for the learning day.</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">G</div><div><div className="tstep-action">Start the project and open it inside Cursor</div><div className="tstep-body">Make sure you are in <strong>Agent</strong> mode. Then send this prompt:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Open my simple browser and start my development server."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Cursor will install dependencies, start the server, and open your project in the Simple Browser — all in one go. You should see the three-panel shell with a working chatbot on the right. If it asks you to confirm anything, click <strong>Accept</strong>.</div></div><div className="callout info"><div className="callout-icon">💡</div><div className="callout-text">You may see a warning about a Node file that cannot be opened — this is harmless. Dismiss it or move it to Trash and carry on.</div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🌐</span><span className="tstep-img-lbl">Screenshot placeholder · Simple Browser open inside Cursor</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">H</div><div><div className="tstep-action">Try your first prompt and see the loop in action</div><div className="tstep-body">In <strong>Agent</strong> mode, send this:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Make the reading panel slightly wider than the video panel and add a thin divider between them."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">That single layout change will make the hierarchy feel different immediately — a useful reminder that layout is design.</div></div><div className="callout info"><div className="callout-icon">💡</div><div className="callout-text">If the browser does not refresh automatically, click the reload icon inside the Simple Browser panel.</div></div></div>

        <hr className="divider" />
        <div id="phase-1" className="phase-header"><div className="sec-label">Phase 1</div><div className="phase-title">Understand what you are working with</div><div className="phase-desc">The course frame has three panels and a working AI chatbot. Before redesigning it, understand how each piece is wired together.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">1</div><div><div className="tstep-action">Ask Cursor to explain the project</div><div className="tstep-body">Switch to <strong>Ask</strong> mode and send this prompt.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Explain this project to me like I am a designer who does not write code. What does each file and folder do? How does the AI chatbot work — what is it connected to and what can I change about how it behaves?"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">2</div><div><div className="tstep-action">Click on elements and tweak the CSS</div><div className="tstep-body">The Simple Browser has a built-in CSS inspector that lets you click on any element and adjust its styles directly — no code required.<ul><li>Click the <strong>inspector icon</strong> in the top-right corner of the Simple Browser to activate it</li><li>Now click any element on the page — the reading pane, the AI panel, the video area</li><li>A panel opens showing the element's CSS: colours, padding, font size, border radius, spacing</li><li>You can <strong>edit values directly</strong> in that panel to see what a change looks like in real time — try changing the width of a panel or the padding around the AI chat</li><li>When you find a tweak you like, describe it to Cursor in the chat: <em>"Make the AI panel wider"</em> or <em>"Reduce the padding in the reading pane"</em> — it will make the change permanent</li></ul>This is often the fastest way to design in Cursor: open the inspector, experiment visually, then tell Cursor what to keep.</div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">3</div><div><div className="tstep-action">Know which mode to use and when</div><div className="tstep-body">You learned about the four modes in Phase 0. Here is how to think about them for the rest of the day:<ul><li><strong>Ask</strong> — when you want to understand a file or component before touching it. "How does the AI chatbot work? What controls its system prompt?"</li><li><strong>Plan</strong> — when you have an idea and want to iterate on the approach before committing. "I want to make the AI panel more prominent — what are my options?" Plan shows you what it would do and lets you refine before it executes</li><li><strong>Agent</strong> — when you are ready to implement. "Collapse the video into an overlay and give the AI panel full height." Agent reads your files, writes code, and makes the change</li></ul>A good rhythm: <strong>Ask</strong> to understand, <strong>Plan</strong> to iterate, <strong>Agent</strong> to build.<br /><br />Now try the chatbot — type a question about the course content into the AI panel. Does the response feel like it belongs to the learning experience or like an external tool dropped in? What would a learner mid-video actually want to ask?</div></div></div><div className="callout info"><div className="callout-icon">💡</div><div className="callout-text"><strong>Debugging tip:</strong> If something looks broken, take a screenshot and drag it into the Cursor chat. Ask: <em>"This is what I'm seeing. What went wrong and how do I fix it?"</em></div></div></div>

        <hr className="divider" />
        <div id="phase-2" className="phase-header"><div className="sec-label">Phase 2</div><div className="phase-title">Connect Figma, then build toward your spec</div><div className="phase-desc">Frame 1 in your companion Figma file is the current three-panel layout — already running as your boilerplate. Frame 2 is a redesigned shell that collapses the video into an overlay and gives the AI panel a full-height presence. You will build toward it.</div></div>
        <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '12px', overflow: 'hidden', marginBottom: '20px' }}>
          <div style={{ background: '#1E1E1E', padding: '16px 20px', display: 'flex', alignItems: 'center', gap: '10px' }}><span style={{ fontSize: '16px' }}>🎨</span><div><div style={{ fontSize: '12px', fontWeight: 600, color: '#fff', marginBottom: '2px' }}>Your companion Figma file</div><div style={{ fontSize: '11px', color: '#888' }}>Open this before starting Phase 2 · Link TBD</div></div></div>
          <div style={{ padding: '16px 20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '80px', background: 'linear-gradient(135deg,#1a1a2e,#4a1a6e)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><span style={{ fontSize: '11px', fontWeight: 600, color: 'rgba(255,255,255,0.6)', letterSpacing: '0.06em', textTransform: 'uppercase' as const }}>Already rendered</span></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 1 · Three-panel shell</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>This is your starting point.</div></div></div>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '80px', background: 'linear-gradient(135deg,#F5F7FA,#E8ECF0)', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' as const }}><span style={{ fontSize: '11px', fontWeight: 600, color: '#9AA0AA', letterSpacing: '0.06em', textTransform: 'uppercase' as const }}>Build toward this</span><div style={{ position: 'absolute' as const, top: '8px', right: '8px', background: '#FFF3CD', color: '#92600A', fontSize: '9px', fontWeight: 600, padding: '2px 6px', borderRadius: '3px', letterSpacing: '0.04em' }}>IN FIGMA</div></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 2 · AI-first shell</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>Video as overlay, AI panel full height. Your build target.</div></div></div>
          </div>
          <div style={{ padding: '12px 20px', borderTop: '0.5px solid #E8E8E8', background: '#FAFAFA' }}><div style={{ fontSize: '11px', color: '#5F6B7A', lineHeight: 1.55 }}>The boilerplate includes a <strong>Tailwind config</strong> with CDS colours, typography, and spacing tokens. Cursor will build custom components to match your Figma spec using these tokens — so the output should feel very close to the design. It won't use the coded CDS component library, which requires a more complex front-end setup that's out of scope for today. More on this soon as we develop design-engineering workflows.</div></div>
        </div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">4</div><div><div className="tstep-action">Connect the Figma MCP to Cursor</div><div className="tstep-body">Once connected, Cursor can read any frame in your Figma file directly — layout, styles, content — without you having to describe any of it.<ul><li>Open Cursor Settings with <strong>Cmd+,</strong> and go to the <strong>MCP</strong> tab</li><li>Click <strong>Add MCP Server</strong> and select <strong>Figma</strong></li><li>Follow the authentication steps and return to the chat panel</li></ul></div></div></div><div className="callout info"><div className="callout-icon">💡</div><div className="callout-text"><strong>Where to find the Figma link for your prompts:</strong> In Figma, switch to <strong>Dev mode</strong> using the toggle in the top-right toolbar. Select the frame you want Cursor to read, right-click, and choose <strong>Copy link</strong>. This is the link you will paste into your Cursor prompts in the next steps.</div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🔗</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor MCP settings with Figma connected</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">5</div><div><div className="tstep-action">Point Cursor at Frame 2 and build it</div><div className="tstep-body">In Figma, switch to <strong>Dev mode</strong>, select <strong>Frame 2 · AI-first shell</strong>, copy the frame link, and send this in <strong>Agent</strong> mode.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Using the Figma MCP, read Frame 2 from this link: [link to frame]. Rebuild the layout to match this design — the video panel becomes a floating overlay triggered by a button, and the AI panel takes full height on the right. Keep the chatbot working. Tell me what you built and flag anything you could not replicate."</div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🎨</span><span className="tstep-img-lbl">Screenshot placeholder · Frame 2 alongside rebuilt shell in Simple Browser</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">6</div><div><div className="tstep-action">Fix broken or missing assets</div><div className="tstep-body">When building from a Figma file, some assets may not transfer cleanly — images might be missing, icons could render as blank boxes, or fonts may fall back to system defaults. This is normal and easy to fix.<ul><li>If an <strong>image is missing</strong>, find the original in Figma, export it as PNG or SVG, and drag it into your project's <code>public</code> folder. Then tell Cursor: <em>"Use the image I just added in public/[filename] for this area"</em></li><li>If an <strong>icon is missing</strong> or looks wrong, tell Cursor what you need: <em>"The play button icon is missing from the video panel. Add one using Material Symbols"</em></li><li>If <strong>fonts look wrong</strong>, take a screenshot and ask Cursor to fix the mismatch</li><li>If <strong>colours are off</strong>, use the inspector from Step 2 to compare what you see against the Figma file, then ask Cursor to correct specific values</li></ul></div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">7</div><div><div className="tstep-action">Test the layout and the chatbot</div><div className="tstep-body">Confirm the video overlay opens and closes, the AI panel spans the full height, and the chatbot still responds. Drag a screenshot into Cursor chat to fix any gaps.</div></div></div></div>

        <hr className="divider" />
        <div id="phase-3" className="phase-header"><div className="sec-label">Phase 3</div><div className="phase-title">Go wide — build something new without a spec</div><div className="phase-desc">The spec gave you a layout change. Now push the AI behaviour itself — how it responds, what it knows, when it speaks.</div></div>
        <div className="callout info"><div className="callout-icon">💡</div><div className="callout-text"><strong>Plan mode shines here.</strong> Phase 3 is open-ended — there is no spec to follow. Before jumping into Agent mode, try sending your direction prompt in <strong>Plan</strong> mode first. It will lay out what it intends to change and you can refine the approach before it writes any code. This is especially useful when you are exploring ideas and want to steer before committing.</div></div>
        <div className="dir-grid">
          <div className="dir-card"><div className="dir-label">Direction 1</div><div className="dir-title">Context-aware AI</div><div className="dir-prompt">"Change the AI system prompt so it knows the learner is in Week 2 of the Google Data Analytics certificate and responds with that context. The first message should acknowledge where they are without being asked."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 2</div><div className="dir-title">Proactive nudges</div><div className="dir-prompt">"Add a small AI-generated callout above the reading content that surfaces one key concept from the current lesson — 2 sentences max. It should feel like a study guide note, not a pop-up."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 3</div><div className="dir-title">Reading and focus mode</div><div className="dir-prompt">"Add a 'Focus mode' button that hides the AI panel and expands the reading pane to full width. A persistent tab or edge indicator should make it easy to bring the AI back."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 4</div><div className="dir-title">Quiz integration</div><div className="dir-prompt">"After the learner sends three messages to the AI, have it offer a quick comprehension check — one multiple choice question based on what they've been discussing. Make it feel like a natural part of the conversation."</div></div>
        </div>

        <div className="optional-block">
          <div className="optional-block-head">
            <div style={{ fontSize: '13px', fontWeight: 500 }}>Optional · Send your concepts back to Figma</div>
            <div style={{ fontSize: '10px', fontWeight: 500, letterSpacing: '0.06em', textTransform: 'uppercase' as const, color: '#9AA0AA' }}>Experimental</div>
          </div>
          <div className="optional-block-body">
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>You can send your concepts from your Cursor prototype directly to Figma as editable layers — not a screenshot. The result may not be pixel-perfect, but it gives you real frames you can annotate, duplicate, and design on top of. For best results, switch your model to <strong>claude-opus-4-6</strong> before running this step.</div>
            <div className="optional-inner-prompt tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Capture the UI in a new frame in Figma here: [link to page in Figma]."</div></div>
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>Cursor may ask you to approve or run something — click through whatever it needs. A small Figma capture toolbar will appear at the top of your browser. Navigate to the state you want to capture, then click <strong>Entire screen</strong> to send it to Figma.</div>
            <div style={{ background: '#FFFBF0', borderRadius: '6px', padding: '10px 14px', fontSize: '12px', color: '#92600A', lineHeight: 1.55 }}>The layers in Figma will be editable but may not match your design system exactly. Treat this as a starting point for refinement, not a finished handoff.</div>
          </div>
        </div>

        <hr className="divider" />
        <div className="tips-box">
          <div className="sec-label" style={{ marginBottom: '12px' }}>Prompting tips</div>
          <div className="ri">Describe what you <em>see</em>, not what you think the code should do. "The AI panel feels cramped" beats "set width to 400px".</div>
          <div className="ri">One change at a time. Multi-part prompts produce messy results.</div>
          <div className="ri">If something breaks: "That broke the layout. Undo that change and let's try a different approach."</div>
          <div className="ri">If the output is close: "That's close. The overlay should feel lighter and the close button more visible." Iterate from what it gave you.</div>
          <div className="ri">Cmd+Z undoes Cursor's changes like any other edit.</div>
        </div>
        <div className="reflect">
          <div className="reflect-lbl">Reflect</div>
          <div className="ri">What did Cursor build correctly without you asking? What did it get wrong or miss?</div>
          <div className="ri">When Cursor pulled from Figma — what translated well? What did it struggle to replicate?</div>
          <div className="ri">Open a real Coursera course and compare the frame. What does your version enable that the real one does not?</div>
          <div className="ri">Did moving the AI to a more prominent position change how the experience felt? Would a learner agree?</div>
          <div className="ri">What would you explore next if you had another hour?</div>
        </div>
        <TutorialEnd onSubmit={() => setDialogOpen(true)} />
      </div>
      <SubmitDialog open={dialogOpen} onClose={() => setDialogOpen(false)} onSubmit={(data) => { submitProject(data); navigate('/', { state: { scrollTo: 'gallery-section' } }) }} />
    </>
  )
}
