import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import SubmitDialog from '../components/SubmitDialog'
import PhaseNav from '../components/PhaseNav'
import TutorialEnd from '../components/TutorialEnd'
import { useSubmissions } from '../lib/submissions'

export default function TutorialDashboard() {
  const navigate = useNavigate()
  const { submitProject } = useSubmissions()
  const [dialogOpen, setDialogOpen] = useState(false)
  return (
    <>
      <div className="t-hero">
        <div className="t-hero-tag">Cursor · Boilerplate B</div>
        <h1>My Learning Dashboard</h1>
        <div className="t-hero-meta">Responsive web · 3 to 6 hours</div>
      </div>
      <PhaseNav />
      <div className="t-body">
        <div className="brief"><div className="brief-lbl">Brief</div><div className="brief-txt">Coursera's logged-in home page has a problem: it's a marketing page pretending to be a personal dashboard. It knows your name, your course, your progress percentage — and then spends most of its space trying to sell you something else. Your job today: fix the center of gravity. The boilerplate gives you a simple version of the current logged-in home. Frame 2 shifts toward the learner's actual data — skills, streaks, pace, a calendar of activity. Build toward that. Then push further: make the platform feel like it's genuinely rooting for the learner to finish.</div></div>

        <div id="phase-0" className="phase-header"><div className="sec-label">Phase 0</div><div className="phase-title">Get set up before your first prompt</div><div className="phase-desc">These steps get Cursor open, your project running, and your brain oriented. Do them in order.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">A</div><div><div className="tstep-action">Download the boilerplate and save your project</div><div className="tstep-body">Download the starter file for this tutorial and unzip it on your machine. You will be working locally for the whole day — no cloud setup needed right now.<ul><li>Download the zip file from <a href="https://drive.google.com/file/d/1ia9X8_hG5usBq5jXNgfNsamwxfXu17oK/view?usp=drive_link" target="_blank" rel="noreferrer"><strong>Boilerplate-Dashboard-Start.zip</strong></a></li><li>Unzip it — you should see a folder called <strong>Boilerplate-Dashboard-Start</strong></li><li>Rename it to something like <strong>dashboard-yourname</strong></li><li>Move it somewhere easy to find, like your <strong>Desktop</strong> or <strong>Documents</strong> folder</li></ul>At the end of the day, you can upload your project folder to your personal Google Drive as a backup, or follow the advanced Phase 4 steps to push it to GitHub. Don't worry about that now.</div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">B</div><div><div className="tstep-action">Open the folder in Cursor</div><div className="tstep-body">Open Cursor. Go to <strong>File › Open Folder</strong> and navigate to your renamed project folder. Select it and click Open.<ul><li>Wait for the spinner in the bottom-left to stop before moving on</li></ul></div></div></div><div className="tstep-img"><img src="/open-project.png" alt="Cursor start screen showing Open project, Clone repo, and Connect via SSH options" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">C</div><div><div className="tstep-action">Get your bearings in the Cursor interface</div><div className="tstep-body">Take a minute to look around before touching anything.<ul><li><strong>Left panel:</strong> the file explorer — every file in your project. You will mostly work inside <code>app</code> and <code>components</code></li><li><strong>Centre:</strong> the code editor — and where your Simple Browser lives. You'll rarely type here directly.</li><li><strong>Right panel / Cmd+L:</strong> the chat panel — this is where you direct Cursor in plain English</li></ul></div></div></div><div className="tstep-img"><img src="/cursor-interface.png" alt="Cursor interface with file explorer on the left, editor in the centre, and chat panel on the right" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">D</div><div><div className="tstep-action">Set your model to Claude</div><div className="tstep-body">In the chat panel, find the model selector near the top. It may say <strong>Auto</strong> by default.<ul><li>Click it and switch to <strong>claude-opus-4-6-high</strong> (sometimes listed as Opus High) — it is the most capable model and a great default for complex prompts</li><li>For quicker, lower-effort tasks — simple text changes, small CSS tweaks, renaming things — switch to <strong>Opus Medium</strong>. It is faster and uses fewer credits. You can switch between them anytime</li><li>Avoid leaving it on <strong>Auto</strong>, which rotates between models unpredictably — picking a model yourself gives you more consistent results all day</li></ul></div></div></div><div className="tstep-img"><img src="/change-model.png" alt="Cursor model selector showing where to change from Auto to a specific model" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">E</div><div><div className="tstep-action">Understand the four chat modes</div><div className="tstep-body">At the top of the chat panel you will see four modes.<ul><li><strong>Agent</strong> — reads your files, writes code, makes changes. Use this for most prompts</li><li><strong>Ask</strong> — answers questions without changing anything. Use it when you want to understand before acting</li><li><strong>Plan</strong> — shows you what it intends to do before doing it. Useful for bigger changes</li><li><strong>Debug</strong> — helps track down errors. You can ignore it for now</li></ul></div></div></div><div className="tstep-img"><img src="/chat-modes.png" alt="Cursor chat mode selector showing Agent, Plan, Debug, and Ask options" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">F</div><div><div className="tstep-action">Start the project and open it inside Cursor</div><div className="tstep-body">Make sure you are in <strong>Agent</strong> mode. Then send this prompt:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Open my simple browser and start my development server."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Cursor will install dependencies, start the server, and open your project in the Simple Browser — all in one go. If it asks you to confirm anything, click <strong>Run</strong>.</div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text">You may see a warning about a Node file that cannot be opened — this is harmless. Dismiss it or move it to Trash and carry on.</div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>You can also use Chrome or any external browser.</strong> The dev server runs on a local address like <code>http://localhost:5173</code> — copy that URL from the Simple Browser's address bar and open it in Chrome. This gives you access to Chrome DevTools for inspecting elements, checking layout, and debugging alongside Cursor.</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">G</div><div><div className="tstep-action">Try your first prompt and see the loop in action</div><div className="tstep-body">Stay in <strong>Agent</strong> mode and send this:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Change the greeting to 'Welcome back, Alex' and make it the most prominent text on the page."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Watch the file update, then check the Simple Browser. That loop — prompt, update, react — is the whole workflow.</div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text">If the browser does not refresh automatically, click the reload icon inside the Simple Browser panel.</div></div></div>

        <hr className="divider" />
        <div id="phase-1" className="phase-header"><div className="sec-label">Phase 1</div><div className="phase-title">Understand what you are working with</div><div className="phase-desc">Before changing anything significant, get a clear picture of what the boilerplate contains.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">1</div><div><div className="tstep-action">Ask Cursor to explain the project</div><div className="tstep-body">Switch to <strong>Ask</strong> mode and send this prompt. Read the full response before moving on. This is a good moment to switch your model to <strong>Opus Medium</strong> — Ask mode questions don't need the full power of Opus High, and it's faster.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Explain this project to me like I am a designer who does not write code. What does each file and folder do? What would I see in the browser if I changed something in each one?"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">2</div><div><div className="tstep-action">Click on elements and tweak the CSS</div><div className="tstep-body">The browser inspector lets you edit CSS values directly on the page in real time — try changing a border radius, a colour, or a font size. The changes appear instantly. This is useful for quick visual experiments where you want to see something before committing to it.<br /><br />Click the <strong>inspector icon</strong> in the top-right corner of the Simple Browser to activate it — it looks like this: <img src="/inspector-icon.png" alt="Inspector icon" style={{ height: '40px', verticalAlign: 'middle', borderRadius: '4px', margin: '0 2px' }} /> — then click any element on the page. A panel opens showing its CSS: colours, padding, font size, border radius, spacing.<br /><br />When you find something you like, you have two options:<ul><li><strong>Click Apply</strong> — the inspector writes the change directly into the file. Fast, no prompting required. The risk: it can be imprecise — inspectors sometimes apply changes to the wrong selector or create inline styles that conflict with your stylesheet later. Good for small, confident tweaks.</li><li><strong>Describe it to Cursor</strong> — tell Cursor what you want in plain language: <em>"Make the cards rounder"</em> or <em>"Increase the heading font size to match the hierarchy in the rest of the page."</em> Cursor finds the right place in the code and makes a clean, permanent change. Slower, but more reliable — especially for anything structural or anything you might want to revisit later.</li></ul>A good rule of thumb: use the inspector to explore, use Cursor to commit.</div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">3</div><div><div className="tstep-action">Know which mode to use and when</div><div className="tstep-body">You learned about the four modes in Phase 0. Here is how to think about them for the rest of the day:<ul><li><strong>Ask</strong> — when you want to understand a file or component before touching it. "What does this component do? What data does it use?"</li><li><strong>Plan</strong> — when you have an idea and want to iterate on the approach before committing. "I want to redesign this layout — what are my options?" Plan shows you what it would do and lets you refine before it executes</li><li><strong>Agent</strong> — when you are ready to implement. "Change the layout and add a loading state." Agent reads your files, writes code, and makes the change</li></ul>A good rhythm: <strong>Ask</strong> to understand, <strong>Plan</strong> to iterate, <strong>Agent</strong> to build.<br /><br />Spend a minute clicking around the boilerplate in the Simple Browser. What is the most important thing on the page? What feels unfinished? Keep that in mind as you move into Phase 2.</div></div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>Debugging tip:</strong> If something looks broken at any point, take a screenshot and drag it into the Cursor chat. Ask: <em>"This is what I'm seeing. What went wrong and how do I fix it?"</em> Cursor can read the screenshot and diagnose the issue directly.</div></div></div>

        <hr className="divider" />
        <div id="phase-2" className="phase-header"><div className="sec-label">Phase 2</div><div className="phase-title">Connect Figma, then build toward your spec</div><div className="phase-desc">Frame 1 is the current logged-in home — marketing-heavy, course cards dominant, progress widget secondary. Frame 2 is the Momentum view — skills data front and center, a weekly activity calendar, streak indicator, pace insight, certificates. Course recommendations still present but no longer the main event.</div></div>
        <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '12px', overflow: 'hidden', marginBottom: '20px' }}>
          <div style={{ background: '#1E1E1E', padding: '16px 20px', display: 'flex', alignItems: 'center', gap: '10px' }}><span style={{ fontSize: '16px' }}>🎨</span><div><div style={{ fontSize: '12px', fontWeight: 600, color: '#fff', marginBottom: '2px' }}>Your companion Figma file</div><div style={{ fontSize: '11px', color: '#888' }}>Open this before starting Phase 2 · <a href="https://www.figma.com/design/IRfqpsrkm6dSkbY0CcYNYD/AI-Learning-Day---Figma-companion-file--Dashboard--Make-a-copy-?node-id=1-2&t=ZZGw6TZhwmpiq9vd-1" target="_blank" rel="noreferrer" style={{ color: '#6B9FFF', textDecoration: 'underline' }}>Open in Figma</a></div></div></div>
          <div style={{ padding: '16px 20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '140px', overflow: 'hidden', position: 'relative' as const }}><img src="/dashboard-frame1.png" alt="Coursera logged-in home page showing progress widget and course recommendations" style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top', display: 'block' }} /><div style={{ position: 'absolute' as const, bottom: '8px', left: '8px', background: '#0056D2', color: '#fff', fontSize: '9px', fontWeight: 600, padding: '2px 7px', borderRadius: '3px', letterSpacing: '0.04em' }}>BUILT IN CURSOR</div></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 1 · Current dashboard</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>This is your starting point.</div></div></div>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '140px', overflow: 'hidden', position: 'relative' as const }}><img src="/dashboard-frame2.png" alt="Coursera dashboard Momentum view with skills, streaks, pace and activity calendar" style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top', display: 'block' }} /><div style={{ position: 'absolute' as const, bottom: '8px', left: '8px', background: '#FFF3CD', color: '#92600A', fontSize: '9px', fontWeight: 600, padding: '2px 7px', borderRadius: '3px', letterSpacing: '0.04em' }}>READY IN FIGMA</div></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 2 · Momentum view</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>Skills, streaks, pace, calendar. Your build target.</div></div></div>
          </div>
          <div style={{ padding: '12px 20px', borderTop: '0.5px solid #E8E8E8', background: '#FAFAFA' }}><div style={{ fontSize: '11px', color: '#5F6B7A', lineHeight: 1.55 }}>The boilerplate includes a <strong>Tailwind config</strong> with CDS colours, typography, and spacing tokens. Cursor will build custom components to match your Figma spec using these tokens — so the output should feel very close to the design. It won't use the coded CDS component library, which requires a more complex front-end setup that's out of scope for today. More on this soon as we develop design-engineering workflows.</div></div>
        </div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">4</div><div><div className="tstep-action">Connect the Figma MCP to Cursor</div><div className="tstep-body">Once connected, Cursor can read any frame in your Figma file directly — layout, styles, content — without you having to describe any of it.<ul><li>Open Cursor Settings with <strong>Cmd+,</strong> and go to the <strong>MCP</strong> tab</li><li>Click <strong>Add MCP Server</strong> and select <strong>Figma</strong></li><li>Follow the authentication steps</li><li>Once Figma shows as connected, come back to the chat panel</li></ul></div></div></div><div className="tstep-img"><img src="/cursor-mcp-settings.png" alt="Cursor Tools & MCP settings showing Figma connected with 13 tools enabled" /></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>Where to find the Figma link for your prompts:</strong> In Figma, switch to <strong>Dev mode</strong> using the toggle in the bottom toolbar (while in Edit mode). You have two options: right-click a frame and choose <strong>Copy link</strong>, or select the frame and click <strong>Copy example prompt</strong> in the right panel — either gives you the link to paste into Cursor.</div></div><div className="tstep-img"><img src="/figma-dev-mode.png" alt="Figma toolbar showing the Dev Mode toggle in the top-right corner" /><img src="/figma-mcp-panel.png" alt="Figma MCP panel showing the Copy example prompt with a Figma file link" /></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">5</div><div><div className="tstep-action">Point Cursor at Frame 2 and build it</div><div className="tstep-body">In Figma, switch to <strong>Dev mode</strong>. Select <strong>Frame 2 · Momentum view</strong>, copy the frame link, and send this prompt in <strong>Agent</strong> mode.<br /><br />The Figma frame shows you a new layout — but a layout alone does not tell Cursor what to prioritise. It cannot tell from the frame which data is real, which components to keep, or why skills should sit above course cards instead of below them. That context is what the prompt provides. If Cursor reads the frame and rebuilds without it, you often get the visual shape of the design with none of the hierarchy decisions that make it meaningful. The extra guidance closes that gap.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Using the Figma MCP, read Frame 2 from this link: [link to frame]. Rebuild the dashboard layout to match this design — hierarchy, spacing, colours, and components. Keep all the existing data. Tell me what you built and flag anything you could not replicate."</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">6</div><div><div className="tstep-action">Implement the responsive views</div><div className="tstep-body">Send this prompt to implement the responsive layout from Figma.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Implement the responsive view according to this design from Figma: [link to frame]"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">7</div><div><div className="tstep-action">Check the hierarchy before moving on</div><div className="tstep-body">Compare the Simple Browser against Frame 2 in Figma. Check two things specifically:<ul><li>The <strong>progress card and resume button</strong> are still prominent above the fold — they should be the first thing a returning learner sees</li><li>The <strong>skills section reads as data</strong> — skill names, levels, progress — not as a list of courses repackaged with a different label</li></ul>If either looks wrong, drag a screenshot into Cursor chat and describe what needs to change.</div></div></div><div className="callout info"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>Debugging tip:</strong> If something looks broken, take a screenshot and drag it into the Cursor chat. Ask: <em>"This is what I'm seeing. What went wrong and how do I fix it?"</em></div></div></div>

        <hr className="divider" />
        <div id="phase-3" className="phase-header"><div className="sec-label">Phase 3</div><div className="phase-title">Go wide — push further than the spec</div><div className="phase-desc">Phase 2 was about accuracy. Phase 3 is about going somewhere Frame 2 doesn't. Pick one direction.</div></div>
        <div className="callout info standalone"><div className="callout-header"><span className="callout-icon">💡</span><span className="callout-label">Tips</span></div><div className="callout-text"><strong>Plan mode shines here.</strong> Phase 3 is open-ended — there is no spec to follow. Before jumping into Agent mode, try sending your direction prompt in <strong>Plan</strong> mode first. It will lay out what it intends to change and you can refine the approach before it writes any code. This is especially useful when you are exploring ideas and want to steer before committing.</div></div>
        <div className="dir-grid">
          <div className="dir-card"><div className="dir-label">Direction 1</div><div className="dir-title">Pace and prediction</div><div className="dir-prompt">"The Momentum view shows past activity. Add a forward-looking layer: based on the learner's current pace of 52 minutes per session, show them when they'll finish — 'At this rate, you'll complete this 2 weeks ahead of your February 15th goal.' Make it feel like insight, not pressure."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 2</div><div className="dir-title">The day's agenda</div><div className="dir-prompt">"Replace the trending courses section entirely. Instead, give the learner a 'today' view — one recommended item to complete, one skill to make progress on, one thing they left unfinished. Three items, nothing more. It should feel like a thoughtful suggestion, not an algorithm."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 3</div><div className="dir-title">Skill gaps made visible</div><div className="dir-prompt">"The skills section in Frame 2 shows progress bars. Push it further: add a layer that shows what skills the learner is missing for their stated goal, and which course would fill the biggest gap. Make the gap feel like an opportunity, not a deficiency."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 4</div><div className="dir-title">Streak as identity</div><div className="dir-prompt">"The 1-week streak in Frame 2 is a small badge. Make it a real design element — something that changes the feel of the page when it's active, and acknowledges when it breaks without making the learner feel bad. Streak protection, streak recovery, streak celebration — pick one and do it well."</div></div>
        </div>

        <div className="optional-block">
          <div className="optional-block-head">
            <div style={{ fontSize: '13px', fontWeight: 500 }}>Optional · Send your concepts back to Figma</div>
            <div style={{ fontSize: '10px', fontWeight: 500, letterSpacing: '0.06em', textTransform: 'uppercase' as const, color: '#9AA0AA' }}>Experimental</div>
          </div>
          <div className="optional-block-body">
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>You can send your concepts from your Cursor prototype directly to Figma as editable layers — not a screenshot. The result may not be pixel-perfect, but it gives you real frames you can annotate, duplicate, and design on top of. For best results, switch your model to <strong>claude-opus-4-6</strong> before running this step.</div>
            <div className="optional-inner-prompt tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Capture the UI in a new frame in Figma here: [link to page in Figma]."</div></div>
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>Cursor may ask you to approve or run something — click through whatever it needs. A small Figma capture toolbar will appear at the top of your browser. Navigate to the state you want to capture, then click <strong>Entire screen</strong> to send it to Figma.</div>
            <div style={{ background: '#FFFBF0', borderRadius: '6px', padding: '10px 14px', fontSize: '12px', color: '#92600A', lineHeight: 1.55 }}>The layers in Figma will be editable but may not match your design system exactly. Treat this as a starting point for refinement, not a finished handoff.</div>
          </div>
        </div>

        <hr className="divider" />
        <div className="tips-box">
          <div className="sec-label" style={{ marginBottom: '12px' }}>Prompting tips</div>
          <div className="ri">Describe what you <em>see</em>, not what you think the code should do. "The progress bar feels too subtle" beats "increase opacity to 100%".</div>
          <div className="ri">One change at a time. Multi-part prompts produce messy results.</div>
          <div className="ri">If something breaks: "That broke the layout. Undo that change and let's try a different approach."</div>
          <div className="ri">If the output is close: "That's close. The streak number should be bigger and the label smaller." Iterate from what it gave you.</div>
          <div className="ri">Cmd+Z undoes Cursor's changes like any other edit.</div>
        </div>
        <div className="reflect">
          <div className="reflect-lbl">Reflect</div>
          <div className="ri">Frame 1 and Frame 2 show the same data in a different hierarchy. What did shifting the hierarchy actually change about how the page felt?</div>
          <div className="ri">Did Cursor understand the difference between a marketing layout and a personal dashboard? Where did it get it wrong?</div>
          <div className="ri">If a learner opened your version every morning for a month, would it help them finish? What's still missing?</div>
          <div className="ri">What would you explore next if you had another hour?</div>
        </div>
        <TutorialEnd onSubmit={() => setDialogOpen(true)} />
      </div>
      <SubmitDialog open={dialogOpen} onClose={() => setDialogOpen(false)} onSubmit={(data) => { submitProject(data); navigate('/', { state: { scrollTo: 'gallery-section' } }) }} />
    </>
  )
}
