import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import SubmitDialog from '../components/SubmitDialog'
import PhaseNav from '../components/PhaseNav'
import TutorialEnd from '../components/TutorialEnd'
import { useSubmissions } from '../lib/submissions'

export default function TutorialDashboard() {
  const navigate = useNavigate()
  const { submitProject } = useSubmissions()
  const [dialogOpen, setDialogOpen] = useState(false)
  return (
    <>
      <div className="t-hero">
        <div className="t-hero-tag">Cursor · Boilerplate B</div>
        <h1>My Learning Dashboard</h1>
        <div className="t-hero-meta">Responsive web · 3 to 6 hours</div>
      </div>
      <PhaseNav />
      <div className="t-body">
        <div className="brief"><div className="brief-lbl">Brief</div><div className="brief-txt">The logged-in home page is the first thing a returning learner sees — and right now it is mostly a list. Your job today: redesign how the platform communicates momentum. The boilerplate gives you a working dashboard shell with enrolled courses, a progress module, and a "pick up where you left off" widget. Make it feel like the platform is paying attention.</div></div>
        <div className="t-img"><span style={{ fontSize: '24px' }}>🖼️</span><span className="lbl">Screenshot placeholder · Boilerplate B running in browser</span></div>

        <div id="phase-0" className="phase-header"><div className="sec-label">Phase 0</div><div className="phase-title">Get set up before your first prompt</div><div className="phase-desc">These steps get Cursor open, your project running, and your brain oriented. Do them in order.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">A</div><div><div className="tstep-action">Download the boilerplate and save your project</div><div className="tstep-body">Download the starter file for this tutorial and unzip it on your machine. You will be working locally for the whole day — no cloud setup needed right now.<ul><li>Download the zip file from <strong>[link TBD]</strong></li><li>Unzip it — you should see a folder called <strong>boilerplate-b-dashboard</strong></li><li>Rename it to something like <strong>dashboard-yourname</strong></li><li>Move it somewhere easy to find, like your <strong>Desktop</strong> or <strong>Documents</strong> folder</li></ul>At the end of the day, you can upload your project folder to your personal Google Drive as a backup, or follow the advanced Phase 4 steps to push it to GitHub. Don't worry about that now.</div></div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">B</div><div><div className="tstep-action">Open the folder in Cursor</div><div className="tstep-body">Open Cursor. Go to <strong>File › Open Folder</strong> and navigate to your renamed project folder. Select it and click Open.<ul><li>Wait for the spinner in the bottom-left to stop before moving on</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🖥️</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor with folder open</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">C</div><div><div className="tstep-action">Get your bearings in the Cursor interface</div><div className="tstep-body"><ul><li><strong>Left panel:</strong> the file explorer — you will mostly work in <code>app</code> and <code>components</code></li><li><strong>Centre:</strong> the code editor — and where your Simple Browser lives. You'll rarely type here directly.</li><li><strong>Right panel / Cmd+L:</strong> the chat panel</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🗂️</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor interface annotated</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">D</div><div><div className="tstep-action">Set your model to Claude</div><div className="tstep-body"><ul><li>Click it and switch to one of the Claude models — Opus is a top performer right now if it's available</li><li>Auto rotates between models unpredictably — a fixed model gives you consistent results all day</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🤖</span><span className="tstep-img-lbl">Screenshot placeholder · Model selector</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">E</div><div><div className="tstep-action">Understand the four chat modes</div><div className="tstep-body"><ul><li><strong>Agent</strong> — reads files, writes code, makes changes. Use this for most prompts</li><li><strong>Ask</strong> — answers questions without changing anything</li><li><strong>Plan</strong> — shows you what it intends to do before doing it</li><li><strong>Debug</strong> — helps track down errors</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>💬</span><span className="tstep-img-lbl">Screenshot placeholder · Chat mode selector</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">F</div><div><div className="tstep-action">Start the project and open it inside Cursor</div><div className="tstep-body">Make sure you are in <strong>Agent</strong> mode. Then send this prompt:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Open my simple browser and start my development server."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Cursor will install dependencies, start the server, and open your project in the Simple Browser — all in one go. If it asks you to confirm anything, click <strong>Accept</strong>.</div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🌐</span><span className="tstep-img-lbl">Screenshot placeholder · Simple Browser open inside Cursor</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn grey">G</div><div><div className="tstep-action">Try your first prompt and see the loop in action</div><div className="tstep-body">Stay in <strong>Agent</strong> mode and send this:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Change the greeting to 'Welcome back, Alex' and make it the most prominent text on the page."</div></div><div className="tstep-head" style={{ paddingTop: '12px' }}><div style={{ width: '28px', flexShrink: 0 }}></div><div className="tstep-body">Watch the file update, then check the Simple Browser. That loop — prompt, update, react — is the whole workflow.</div></div><div className="callout info"><div className="callout-icon">💡</div><div className="callout-text">If the browser does not refresh automatically, click the reload icon inside the Simple Browser panel.</div></div></div>

        <hr className="divider" />
        <div id="phase-1" className="phase-header"><div className="sec-label">Phase 1</div><div className="phase-title">Understand what you are working with</div><div className="phase-desc">Before changing anything significant, get a clear picture of what the boilerplate contains.</div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">1</div><div><div className="tstep-action">Ask Cursor to explain the project</div><div className="tstep-body">Switch to <strong>Ask</strong> mode and send this prompt.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Explain this project to me like I am a designer who does not write code. What does each file and folder do? What would I see in the browser if I changed something in each one?"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">2</div><div><div className="tstep-action">Inspect the progress widget</div><div className="tstep-body">In the file explorer, click <code>components/ProgressWidget.tsx</code>. Stay in <strong>Ask</strong> mode and send this:</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"What is this component doing? What data is it using, what does it show the learner, and what can I change without breaking the rest of the page?"</div></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">3</div><div><div className="tstep-action">Look at the boilerplate with fresh eyes</div><div className="tstep-body">Spend two minutes in the Simple Browser as a returning learner.<ul><li>What does the page communicate about your progress?</li><li>What is the most important action and how hard is it to find?</li><li>What feels like filler that a real learner would ignore?</li></ul></div></div></div><div className="callout info"><div className="callout-icon">💡</div><div className="callout-text"><strong>Debugging tip:</strong> If something looks broken, take a screenshot and drag it into the Cursor chat. Ask: <em>"This is what I'm seeing. What went wrong and how do I fix it?"</em></div></div></div>

        <hr className="divider" />
        <div id="phase-2" className="phase-header"><div className="sec-label">Phase 2</div><div className="phase-title">Connect Figma, then build toward your spec</div><div className="phase-desc">Your companion Figma file has one frame already rendered as the boilerplate. The second frame is a redesigned dashboard state. You will connect Figma to Cursor, read that design, and build toward it.</div></div>
        <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '12px', overflow: 'hidden', marginBottom: '20px' }}>
          <div style={{ background: '#1E1E1E', padding: '16px 20px', display: 'flex', alignItems: 'center', gap: '10px' }}><span style={{ fontSize: '16px' }}>🎨</span><div><div style={{ fontSize: '12px', fontWeight: 600, color: '#fff', marginBottom: '2px' }}>Your companion Figma file</div><div style={{ fontSize: '11px', color: '#888' }}>Open this before starting Phase 2 · Link TBD</div></div></div>
          <div style={{ padding: '16px 20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '80px', background: 'linear-gradient(135deg,#003D35,#007A6E)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}><span style={{ fontSize: '11px', fontWeight: 600, color: 'rgba(255,255,255,0.6)', letterSpacing: '0.06em', textTransform: 'uppercase' }}>Already rendered</span></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 1 · Current dashboard</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>This is your starting point.</div></div></div>
            <div style={{ border: '0.5px solid #E8E8E8', borderRadius: '8px', overflow: 'hidden' }}><div style={{ height: '80px', background: 'linear-gradient(135deg,#F5F7FA,#E8ECF0)', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative' as const }}><span style={{ fontSize: '11px', fontWeight: 600, color: '#9AA0AA', letterSpacing: '0.06em', textTransform: 'uppercase' }}>Build toward this</span><div style={{ position: 'absolute' as const, top: '8px', right: '8px', background: '#FFF3CD', color: '#92600A', fontSize: '9px', fontWeight: 600, padding: '2px 6px', borderRadius: '3px', letterSpacing: '0.04em' }}>IN FIGMA</div></div><div style={{ padding: '10px 12px' }}><div style={{ fontSize: '12px', fontWeight: 500, marginBottom: '3px' }}>Frame 2 · Momentum view</div><div style={{ fontSize: '11px', color: '#9AA0AA', lineHeight: 1.4 }}>A redesigned layout that leads with progress, not a list. Your build target.</div></div></div>
          </div>
          <div style={{ padding: '12px 20px', borderTop: '0.5px solid #E8E8E8', background: '#FAFAFA' }}><div style={{ fontSize: '11px', color: '#5F6B7A', lineHeight: 1.55 }}>The file uses the <strong>CDS design system library</strong>, already connected.</div></div>
        </div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">4</div><div><div className="tstep-action">Connect the Figma MCP to Cursor</div><div className="tstep-body">Once connected, Cursor can read any frame in your Figma file directly.<ul><li>Open Cursor Settings with <strong>Cmd+,</strong> and go to the <strong>MCP</strong> tab</li><li>Click <strong>Add MCP Server</strong> and select <strong>Figma</strong></li><li>Follow the authentication steps</li><li>Once Figma shows as connected, come back to the chat panel</li></ul></div></div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🔗</span><span className="tstep-img-lbl">Screenshot placeholder · Cursor MCP settings with Figma connected</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">5</div><div><div className="tstep-action">Point Cursor at Frame 2 and build it</div><div className="tstep-body">In Figma, switch to <strong>Dev mode</strong>. Select <strong>Frame 2 · Momentum view</strong>, copy the frame link, and send this prompt in <strong>Agent</strong> mode.</div></div></div><div className="tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Using the Figma MCP, read Frame 2 from this link: [link to frame]. Rebuild the dashboard layout to match this design — hierarchy, spacing, colours, and components. Keep all the existing data. Tell me what you built and flag anything you could not replicate."</div></div><div className="tstep-img"><span style={{ fontSize: '20px' }}>🎨</span><span className="tstep-img-lbl">Screenshot placeholder · Frame 2 alongside built dashboard in Simple Browser</span></div></div>
        <div className="tstep"><div className="tstep-head"><div className="sn blue">6</div><div><div className="tstep-action">Test the rebuilt layout</div><div className="tstep-body">Check the Simple Browser against Frame 2 in Figma. Confirm the hierarchy reads correctly, the progress data is intact, and the primary action is clear. Drag a screenshot into Cursor chat to fix any gaps.</div></div></div></div>

        <hr className="divider" />
        <div id="phase-3" className="phase-header"><div className="sec-label">Phase 3</div><div className="phase-title">Go wide — build something new without a spec</div><div className="phase-desc">Phase 2 was about accuracy. Phase 3 is exploration. Put the Figma file away and push the dashboard into territory the spec does not cover.</div></div>
        <div className="dir-grid">
          <div className="dir-card"><div className="dir-label">Direction 1</div><div className="dir-title">Streak and motivation</div><div className="dir-prompt">"Add a learning streak indicator showing the learner has studied 7 days in a row. It should feel like an achievement worth protecting, not a gamification gimmick."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 2</div><div className="dir-title">Next best action</div><div className="dir-prompt">"The dashboard currently shows everything equally. Add a single high-priority callout — 'You have a quiz due Friday' — that sits above everything else. It should feel urgent without being alarming."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 3</div><div className="dir-title">Completion and celebration</div><div className="dir-prompt">"One of the courses is 100% complete. Change how that card looks — it should feel finished and distinct from active courses. Don't just add a checkmark."</div></div>
          <div className="dir-card"><div className="dir-label">Direction 4</div><div className="dir-title">Time awareness</div><div className="dir-prompt">"Add a small estimate to the primary course card: 'About 22 minutes to finish this week's module.' It should feel helpful, not pressuring."</div></div>
        </div>

        <div className="optional-block">
          <div className="optional-block-head">
            <div style={{ fontSize: '13px', fontWeight: 500 }}>Optional · Send your concepts back to Figma</div>
            <div style={{ fontSize: '10px', fontWeight: 500, letterSpacing: '0.06em', textTransform: 'uppercase' as const, color: '#9AA0AA' }}>Experimental</div>
          </div>
          <div className="optional-block-body">
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>You can send your concepts from your Cursor prototype directly to Figma as editable layers — not a screenshot. The result may not be pixel-perfect, but it gives you real frames you can annotate, duplicate, and design on top of. For best results, switch your model to <strong>claude-opus-4-6</strong> before running this step.</div>
            <div className="optional-inner-prompt tstep-prompt"><div className="prompt-lbl">Send this prompt</div><div className="prompt-text">"Capture the UI in a new frame in Figma here: [link to page in Figma]."</div></div>
            <div style={{ fontSize: '13px', color: '#5F6B7A', lineHeight: 1.6 }}>Cursor may ask you to approve or run something — click through whatever it needs. A small Figma capture toolbar will appear at the top of your browser. Navigate to the state you want to capture, then click <strong>Entire screen</strong> to send it to Figma.</div>
            <div style={{ background: '#FFFBF0', borderRadius: '6px', padding: '10px 14px', fontSize: '12px', color: '#92600A', lineHeight: 1.55 }}>The layers in Figma will be editable but may not match your design system exactly. Treat this as a starting point for refinement, not a finished handoff.</div>
          </div>
        </div>

        <hr className="divider" />
        <div className="tips-box">
          <div className="sec-label" style={{ marginBottom: '12px' }}>Prompting tips</div>
          <div className="ri">Describe what you <em>see</em>, not what you think the code should do. "The progress bar feels too subtle" beats "increase opacity to 100%".</div>
          <div className="ri">One change at a time. Multi-part prompts produce messy results.</div>
          <div className="ri">If something breaks: "That broke the layout. Undo that change and let's try a different approach."</div>
          <div className="ri">If the output is close: "That's close. The streak number should be bigger and the label smaller." Iterate from what it gave you.</div>
          <div className="ri">Cmd+Z undoes Cursor's changes like any other edit.</div>
        </div>
        <div className="reflect">
          <div className="reflect-lbl">Reflect</div>
          <div className="ri">What did Cursor build correctly without you asking? What did it get wrong or miss?</div>
          <div className="ri">When Cursor pulled from Figma — what translated well? What did it struggle to replicate?</div>
          <div className="ri">Log in to coursera.org and look at your real dashboard. What does your version do that the real one does not? What did you lose?</div>
          <div className="ri">If a learner opened this page on a Monday morning, what would they do first? Is that the right thing?</div>
          <div className="ri">What would you explore next if you had another hour?</div>
        </div>
        <TutorialEnd onSubmit={() => setDialogOpen(true)} />
      </div>
      <SubmitDialog open={dialogOpen} onClose={() => setDialogOpen(false)} onSubmit={(data) => { submitProject(data); navigate('/', { state: { scrollTo: 'gallery-section' } }) }} />
    </>
  )
}
